language: php

notifications:
  email: false

php:
  - "7.4"
  - "8.0"
  - "8.1"

install:
  - composer install

script:
  - find {src,tests} -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - composer phpcs
  - composer unit
