language: php

notifications:
  email: false

php:
  - "7.3"
  - "7.4"

install:
  - composer install

script:
  - find {src,tests} -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - vendor/bin/phpcs --standard=PSR12 --extensions=php src tests
  - vendor/bin/phpunit tests
