# {{ $ids := "composer-plugin" }}ids: {{ print $ids }}
# {{ $org := "oxid-esales" }}organisation: {{ print $org }}
# {{ $name := "oxideshop-composer-plugin" }}name: {{ print $name }}

prepare_shop:
  git:
    shop_ref: '{{ .Data.global.git.default_ref }}'

install_module:
  matrix:
    testplan: '["-"]'
  cache:
    prefix: &install_module_prefix 'moduleInstallation-ce-{{ .Github.SHA }}-{{ .Github.RunID }}'
  ids: &ids '{{ print $ids }}'
  activate: ''
  git:
    module:
      url: &git_module_url '{{ .Github.Repository }}'
      ref: '{{ .Github.RefName }}'
  package_name: &package_name '{{ print $org }}/{{ print $name }}'
  path: *ids

phpunit:
  matrix:
    testplan: '["~/defaults/module_phpunit_unit.yml","~/defaults/module_phpunit_integration.yml"]'
  load_shop: *install_module_prefix

codeception:
  matrix:
    testplan: 'skip'
  load_shop: *install_module_prefix

runtest:
  matrix:
    testplan: 'skip'
  load_shop: *install_module_prefix

sonarcloud:
  matrix:
    testplan: 'skip'

styles:
  matrix:
    testplan: 'skip'
  load_shop: *install_module_prefix

finish:
  slack_title: 'Component {{ print $name }} ({{ .Data.global.git.shop_ref }}) on {{ .Github.Repository }} by {{ .Github.Actor }}'
