install:
  cache:
    prepared_shop: false
  git:
    repository: 'OXID-eSales/oxideshop_composer_plugin'
    ref: &ref '{{ .Github.RefName }}'
    shop_url: 'https://github.com/OXID-eSales/oxideshop_composer_plugin.git'
    shop_ref: *ref
  composer:
    root_url: ''
    transform: ''
  custom_script_container: ''

install_shop_with_modules:
  skip_shop_installation: true
  composer:
    root_url: ''

runscript: &runscript
  matrix:
    script: |
      [
        "composer_plugin:tests-unit",
      ]
  composer_plugin:
    path: ''

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "composer_plugin:phpcs",
      ]

sonarcloud:
  matrix:
    testplan: 'skip'
