install:
  cache:
    prepared_shop: false

runscript:
  matrix:
    script: |
      [
        "composer_plugin:tests-unit",
      ]
  composer_plugin:
    path: ''

runslim:
  matrix:
    script: |
      [
        "composer_plugin:phpcs-report",
      ]

sonarcloud:
  matrix:
    testplan: 'skip'
