global:
  org: 'oxid-esales'
  name: 'oxideshop-composer-plugin'
  repo: 'OXID-eSales/oxideshop_composer_plugin'

runscript:
  matrix:
    script: |
      [
        "component:~/Integration.sh",
        "component:~/PhpCsReport.sh",
        "component:~/PhpMdReport.sh",
        "component:~/PhpStanReport.sh"
      ]
