name: Auto trigger on push or pull requests

on:
  pull_request: {}
  push: {}

jobs:
  composer_plugin:
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yml@v5
    with:
      testplan: '~/defaults/7.4.x.yaml,~/composer-plugin.yaml,~/_custom.yaml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v5'
      plan_folder: '.github/oxid-esales'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}